services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5433:5432'   # Change the host port to 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
